### ISSUE TITLE
Renewal process?

### ISSUE THREAD

**Issue by ghost** [diafygi/letsencrypt-nosudo#10]
What is the renewal process like? Do you just run again against the same CSR?

**Comment by diafygi** [comment]
Unfortunately, there's not a way to renew certs with this script yet, but I want to make one. It will probably be a new `renew_crt.py --public-key user.pub signed.crt` script.

**Comment by ghost** [comment]
Will gladly help test if you find the time to tackle this

**Comment by niktamerfdp** [comment]
Would love to test this too!

**Comment by lol768** [comment]
Would also be interested in this :)

**Comment by MyIgel** [comment]
_upvote_

**Comment by pcoutin** [comment]
Would it need access to the private keys at all?
I thought of making a cron script or something. have to figure out how to serve a file from nginx for the verification instead of having to start the python http server

**Comment by diafygi** [comment]
@pcoutin no, any implementation of `renew_crt.py` in this repo would not ask for your private key and print the signature commands you need to run in another terminal.

**Comment by diafygi** [comment]
So I've been looking into this, and it appears the there's not really a set renewal process for ACME (yet). So, until the standard for renewal is settled, we'll just have to create new CSR's and request they be signed every 90 days. NOTE: I made a tiny script to this via cron ([acme-tiny](https://github.com/diafygi/acme-tiny)).

Anyway, I'm closing this issue until there is an official way to renew.

**Comment by markstos** [comment]
It would still be helpful to mention something in the README about the state of renewals. Every user of this project will soon find that they are interested in the topic of renewals, especially automating them.
