### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib2'

### ISSUE THREAD

**Issue by ArnaudKleinveld** [diafygi/letsencrypt-nosudo#103]
Hi, upgraded to the latest Fedora recently and was faced with the above error message when I ran python sign_csr.py. Anything I can do to help?

Thanks,
Arnaud

**Comment by ArnaudKleinveld** [comment]
Ran 2to3 -w . on the source root and then when executed the following returns:
Reading pubkey file...
Traceback (most recent call last):
  File "sign_csr.py", line 450, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 46, in sign_csr
    out, re.MULTILINE|re.DOTALL).groups()
  File "/usr/lib64/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

I have tried to fix the type casting errors but every time I fixed one it fell into the next one. Is it still worth fixing this because support from Let’s Encrypt seems to be improved as well?

**Comment by dmitry-grinko** [comment]
@ArnaudKleinveld did you solve it? any news?

**Comment by ArnaudKleinveld** [comment]
@dm-grinko Switching to Certbot appeared to be a better solution at this moment. This project seems to be abandoned.

**Comment by dmitry-grinko** [comment]
> @dm-grinko Switching to Certbot appeared to be a better solution at this moment. This project seems to be abandoned.

got it. thank you
