### ISSUE TITLE
A way to bypass sudo access.

### ISSUE THREAD

**Issue by ITechGeek81** [diafygi/letsencrypt-nosudo#13]
Instead of using sudo python to complete the challenge, can you provide the file and contents to save?

I'm trying to create a certificate on a server that I don't have root/sudo access.

If instead of providing:
sudo python -c "import BaseHTTPServer; \

> ```
> h = BaseHTTPServer.BaseHTTPRequestHandler; \
> h.do_GET = lambda r: r.send_response(200) or r.end_headers() or r.wfile.write('{\"header\": {\"alg\": \"RS256\"}, \"protected\": \"eyJhbGciOiAiUlMyNTYifQ\", \"payload\": \"ewogICAgInRscyI6IGZhbHNlLCAKICAgICJ0b2tlbiI6ICJkbzVaWkMwMHVwZmNFN0tjeEhzOGNyS2FNaE02UFdBdTMtMnVwZ00zRG00IiwgCiAgICAidHlwZSI6ICJzaW1wbGVIdHRwIgp9\", \"signature\": \"Gp5V68da_XdC96piXs1YOhrv4USOQBNnhIL-CMmxvKSigmxAJ8z00xsgWS6nsYD8LPpMVa3GkXhb10qfbymPiWhtMpMYZ31kMLFwgpHrY9xkiNP-WK9Zljz6L-WAzxCOmF1Ov71z_75iEJij86E2f9EmTjDlmDmGAjP9lziII42uyyjjIZg9claU1GtFZUrfXd-uNHHEGHFUpoyLHQcyWCP1T04Xx4q4dY51VeOJNOmIv9csIjkbOma7EqFMAHwYAplAUE45FQ5N9lJvpymD49BoEgQj_kjH-UPnxO3q0QB0i-MJJCiwQYAhMKV618jV9rNE181zJ1FRkX48knMzqoE4oG3yEFUg2D_vAdFG3VCuotnuxrZ7BEzDPWyEm0z8XakxWQW-xHSADtKWRr1qsQCy7qVsoAKnVFQ_1b4rAzET1YfrmhSH4MVhMB5n9tOnjtPQ0OsJVbf0oVLh5AC1rbXe68weOQExDVJgsk56x3FvvwrmdaLe2TnbPJmzpkYUf1OK88e8KmhVYb34veuY1luDOBJQyQ9fOAGZC0F-g7SpWg1lp3hQzf5enkycHMK-fNAfFH7t1m1Ej_CvUuxfBVhI0W8ANpFWL4r8PxTZaZzE6NO38MYgB9nrICiKJuuTQQbsXdjOm22QuxrG1XpWA-vQCtbk-L891Ko6MdAUMzQ\"}'); \
> s = BaseHTTPServer.HTTPServer(('0.0.0.0', 80), h); \
> s.serve_forever()"
> ```

If you could provide an option to save a file on the webserver that would be good.

**Comment by phpfs** [comment]
Good Idea!

**Comment by diafygi** [comment]
> If you could provide an option to save a file on the webserver that would be good.

Interesting, could you please expand more on what you'd like to see? Exactly what would you expect the behavior to be? Mind giving an example of what you want?

**Comment by 0rovan** [comment]
It sure is a nice idea to get a certificate without sudo, but in most cases you still need(and should need) sudo to make application using your new cert.

**Comment by ITechGeek81** [comment]
https://groups.google.com/a/letsencrypt.org/forum/#!topic/client-dev/1DOquAFDajs

http://www.google.com/url?q=http%3A%2F%2Ffree-ssl-certificate.online-domain-tools.com%2F&sa=D&sntz=1&usg=AFQjCNF_g0NvsBxLQMKXC8lvj29F0M404g

I actually did test it our and right now they're using a fake CA (they claim until Let's Encrypt goes live).

That person developed a web interface, and as part of the setup, they provide the user a file that you upload to (website domain)/.well-known/acme-challenge/ to do the validation.  If your client auto-placed that file for me, you could do the validation w/o user input (worst case, ask the user for their webroot as a cmdline option).

**Comment by diafygi** [comment]
@ITechGeek81 Sorry, I'm a bit confused. This script isn't meant to be run on your production server, so it needs to print out stuff you need to do on your server. How exactly do you want that printout to look?

**Comment by ITechGeek81** [comment]
My thought was running it on a production server in which I do not have root access on.

For example a website being run on a shared server w/ cPanel.

**Comment by ITechGeek81** [comment]
But in the case of running it on a non production server, you could save the file and tell people put file A in location B of the production site.

**Comment by diafygi** [comment]
Ok, I think I understand now. Unfortunately, I think that use case is a bit out of scope for this project, but feel free to fork this project and create your own version! Thanks for the feedback!
