### ISSUE TITLE
Many Errors when using this script

### ISSUE THREAD

**Issue by phpfs** [diafygi/letsencrypt-nosudo#14]
At first , i encountered some... 

> Value Error: Zero length field name in format 

...errors (for example in line 21 / 44).

After fixing all that, i got this one:

> Reading pubkey file...
> Traceback (most recent call last):
>   File "sign_csr.py", line 429, in <module>
>     signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email)
>   File "sign_csr.py", line 45, in sign_csr
>     pub_exp = binascii.unhexlify(pub_exp)
> TypeError: Odd-length string

Where is the problem, i don't get it! I also tried pub_exp.strip() to fix it, but it didn't work out that fine!
(I followed your tutorial for creating all certificates!)

**Comment by diafygi** [comment]
Thanks for the bug report. Would you please post the user.pub and domain.csr that you are attempting to use.

**Comment by phpfs** [comment]
I have already regenerated them a lot of times, i think they are not the problem!

**Comment by diafygi** [comment]
Unfortunately, it is very hard to troubleshoot without a specific, reproducible example. Please ask to reopen this bug when you can provide a specific example. Thanks!
