### ISSUE TITLE
Consider driving donations to ISRG instead of EFF?

### ISSUE THREAD

**Issue by konklone** [diafygi/letsencrypt-nosudo#15]
I love EFF dearly, and obviously they're supporting Let's Encrypt, but I think that the [Internet Security Research Group](https://letsencrypt.org/isrg/), as the 501(c)(3) that operates Let's Encrypt and is responsible for its financials, software development, and strategic direction, is the best target for the donations this project drives on its README.

Their [Become a Sponsor](https://letsencrypt.org/become-a-sponsor/) page has a PayPal button at the bottom. I'm not sure the best way to adapt it into a README-friendly link.

@jsha @jmhodges

**Comment by diafygi** [comment]
Unfortunately, I'm a bit more politically motivated and want to support the EFF's other initiatives, too. The fight against mass surveillance is not just Let's Encrypt. It includes lawsuits and education campaigns.
