### ISSUE TITLE
Works great with Hiawatha Webserver

### ISSUE THREAD

**Issue by robotanarchy** [diafygi/letsencrypt-nosudo#17]
Thanks for writing this script, I like that one can read through it quickly and it doesn't contain code to change my configs. (That does not mean, that the official client is bad - it is just not as suited for power users as your script is.)

Now I have Let's Encrypt with Hiawatha working :+1: 

[Here's](https://robotanarchy.space/lets-encrypt-hiawatha/) a quick tutorial I wrote for other Hiawatha users. The only real difference is in creating the final certificate file, which also contains `domain.key`:

```
cat domain.key signed.crt lets-encryt-x1-cross-signed.pem > letsencrypt_hiawatha.crt
```

Thanks for your work @diafygi !

**Comment by diafygi** [comment]
Thanks for the feedback! It's interesting that your setup has you mixing private and public keys in the same file.
