### ISSUE TITLE
Add optional parameter for user.key full path

### ISSUE THREAD

**Issue by ecc256** [diafygi/letsencrypt-nosudo#25]
If user.key is supplied
Either generate (and save) "ready to run" scripts:
openssl dgst -sha256 -sign my_secret_path/user.key -out register_jxcwae.sig register_gtnj7b.json
openssl dgst -sha256 -sign my_secret_path/user.key -out domain_5a64yt.sig domain_ieex7l.json
openssl dgst -sha256 -sign my_secret_path/user.key -out cert_ccna96.sig cert_pf6pwm.json

Or execute “openssl –sign {}” right away.

**Comment by 0rovan** [comment]
I have just done this to my fork, so one of the solution for the above described problem can be found here:
https://github.com/0rovan/letsencrypt-nosudo/commit/975fc7d0f198554bdc49b6b9d141b5d0cb3b88ad

**Comment by diafygi** [comment]
Sorry, this script will never ask for your private key, even optionally. It hasn't been audited and I don't want people to think it's ok to give any old script access to their private key. If you want to fully automate the process and give access to your private key, please use the official letsencrypt client, which has had a ton more review and smarter people working on it.
