### ISSUE TITLE
Multiple domains?

### ISSUE THREAD

**Issue by robotanarchy** [diafygi/letsencrypt-nosudo#26]
Hello,

what would be the syntax to create a working certificate sign request for multiple domains?
For example: `github.com, *.github.com`

It would be nice if you could add this to the [example usage](https://github.com/diafygi/letsencrypt-nosudo#example-use).

Thanks :+1:

**Comment by diafygi** [comment]
I do: https://github.com/diafygi/letsencrypt-nosudo#how-to-use-the-script

```
#Alternatively, if you want both example.com and www.example.com
openssl genrsa 4096 > domain.key
openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:example.com,DNS:www.example.com")) > domain.csr
```

NOTE: Let's Encrypt doesn't allow wildcard domains, so if you include one in your subjectAltName, Let's Encrypt will reject it.
