### ISSUE TITLE
Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-45-generic x86_64) / Traceback included... 

### ISSUE THREAD

**Issue by huggi** [diafygi/letsencrypt-nosudo#27]
DISCLAIMER:
1. I understand it's beta. I'm not a programmer. more the network guy :)
2. My domain is whitelisted at letsencrypt.org
3. I installed letsencrypt-nosudo on my webhoster's Ubuntu 14.04.2 LTS (using git, it was not installed), my unsecure area (http) is at /home/nines9/public_html/, my secure area (https) is at /home/nines9/secure_html/,  I've used a .htaccess script to redirect all HTTP traffic to HTTPS:

```
<IfModule mod_rewrite.c>

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</IfModule>
```

This feature is currently turned OFF, but it takes a few hours to reload the settings, hence the redirect is still in place :(
1. I checked for openssl (OpenSSL 1.0.1f 6 Jan 2014) and python (Python 2.7.6), both there.
2. cd to letsencrypt-nosudo and follow the instructions at: https://github.com/diafygi/letsencrypt-nosudo/#how-to-use-the-script 
3. Output: Before the start

```
nines9@magnesium:~/letsencrypt-nosudo$ ls -lha
total 92K
drwxr-xr-x 3 nines9 users 4.0K Nov 19 19:57 .
drwx---r-x 9 nines9 users 4.0K Nov 19 19:57 ..
drwxr-xr-x 8 nines9 users 4.0K Nov 19 19:57 .git
-rw-r--r-- 1 nines9 users  675 Nov 19 19:57 .gitignore
-rw-r--r-- 1 nines9 users  34K Nov 19 19:57 LICENSE
-rw-r--r-- 1 nines9 users  17K Nov 19 19:57 README.md
-rw-r--r-- 1 nines9 users  17K Nov 19 19:57 sign_csr.py
```
1. Now, let's start..

First command (terminal 1):

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl genrsa 4096 > user.key
Generating RSA private key, 4096 bit long modulus
.................................++
.................................................................................................................................................................++
e is 65537 (0x10001)
```

Second command (terminal 1):

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl rsa -in user.key -pubout > user.pub
writing RSA key
```

Third command (terminal 1):

```
nines9@magnesium:~/letsencrypt-nosudo$ #Alternatively, I want both 9nines.net and www.9nines.net
nines9@magnesium:~/letsencrypt-nosudo$ openssl genrsa 4096 > domain.key
Generating RSA private key, 4096 bit long modulus
.......................................................................................................................................................................................++
.............................................................................++
e is 65537 (0x10001)
nines9@magnesium:~/letsencrypt-nosudo$ openssl req -new -sha256 -key domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:9nines.net,DNS:www.9nines.net")) > domain.csr
```

Fourth command: Terminal 1, switching to Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ python sign_csr.py --public-key user.pub domain.csr > signed.crt
Reading pubkey file...
Found public key!
Reading csr file...
Found domains www.9nines.net, 9nines.net
STEP 1: What is your contact email? (webmaster@9nines.net)     
Building request payloads...
Building request for www.9nines.net...
Building request for 9nines.net...
Building request for CSR...
STEP 2: You need to sign some files (replace 'user.key' with your user private key).

openssl dgst -sha256 -sign user.key -out register_gxKP4_.sig register_fFw75_.json
openssl dgst -sha256 -sign user.key -out domain_l3TNrL.sig domain_b0O1LU.json
openssl dgst -sha256 -sign user.key -out domain_VCB1zQ.sig domain_mjx5UI.json
openssl dgst -sha256 -sign user.key -out cert_J4eZU3.sig cert_WrHIam.json

Press Enter when you've run the above commands in a new terminal window...
```

First command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out register_gxKP4_.sig register_fFw75_.json
```

Second command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out domain_l3TNrL.sig domain_b0O1LU.json
```

Third command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out domain_VCB1zQ.sig domain_mjx5UI.json
```

Fourth command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out cert_J4eZU3.sig cert_WrHIam.json
```

Sixt command: Terminal 1

```
Registering webmaster@9nines.net...
Requesting challenges for www.9nines.net...
Building challenge responses for www.9nines.net...
Requesting challenges for 9nines.net...
Building challenge responses for 9nines.net...
STEP 3: You need to sign some more files (replace 'user.key' with your user private key).

openssl dgst -sha256 -sign user.key -out challenge_fzPMHb.sig challenge_9hvDtS.json
openssl dgst -sha256 -sign user.key -out challenge_ahkiEM.sig challenge_tN2nj0.json

Press Enter when you've run the above commands in a new terminal window...
```

Fifth command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out challenge_fzPMHb.sig challenge_9hvDtS.json
```

Sixt command: Terminal 2

```
nines9@magnesium:~/letsencrypt-nosudo$ openssl dgst -sha256 -sign user.key -out challenge_ahkiEM.sig challenge_tN2nj0.json
```

Seventh command: Terminal 1

```
STEP 4: You need to run this command on www.9nines.net (don't stop the python command until the next step).

sudo python -c "import BaseHTTPServer; \
    h = BaseHTTPServer.BaseHTTPRequestHandler; \
    h.do_GET = lambda r: r.send_response(200) or r.end_headers() or r.wfile.write('vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no.OFd93iap7pzVH0u9CGS6BL7qGaCscvDcA3uyxt-WO7M'); \
    s = BaseHTTPServer.HTTPServer(('0.0.0.0', 80), h); \
    s.serve_forever()"

Press Enter when you've got the python command running on your server...
```

Eight command: Terminal 1

```
Requesting verification for www.9nines.net...
Waiting for www.9nines.net challenge to pass...
Traceback (most recent call last):
  File "sign_csr.py", line 415, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email)
  File "sign_csr.py", line 347, in sign_csr
    raise KeyError("'{}' challenge did not pass: {}".format(i['domain'], challenge_status))
KeyError: "'www.9nines.net' challenge did not pass: {u'status': u'invalid', u'validationRecord': [{u'url': u'http://www.9nines.net/.well-known/acme-challenge/vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no', u'hostname': u'www.9nines.net', u'addressUsed': u'64.62.186.8', u'port': u'80', u'addressesResolved': [u'64.62.186.8']}, {u'url': u'https://www.9nines.net/.well-known/acme-challenge/vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no', u'hostname': u'www.9nines.net', u'addressUsed': u'64.62.186.8', u'port': u'443', u'addressesResolved': [u'64.62.186.8']}], u'keyAuthorization': u'vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no.OFd93iap7pzVH0u9CGS6BL7qGaCscvDcA3uyxt-WO7M', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/ex_fOS2M1_l-3RY5-kZHgnKd6ZxBaXaHW5HcLkJX7XE/435535', u'token': u'vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no', u'error': {u'type': u'urn:acme:error:unauthorized', u'detail': u'Invalid response from http://www.9nines.net/.well-known/acme-challenge/vcDQcSgQoxUI8ZBMkpZzAwnaNefIEQp5grxEtd-O-no [64.62.186.8]: 404'}, u'type': u'http-01'}"
```

That's it. 

OUTPUT of the directory, Terminal 1:

```
nines9@magnesium:~/letsencrypt-nosudo$ ls -lha
total 108K
drwxr-xr-x 3 nines9 users 4.0K Nov 19 20:31 .
drwx---r-x 9 nines9 users 4.0K Nov 19 19:57 ..
-rw-r--r-- 1 nines9 users 1.6K Nov 19 20:10 domain.csr
-rw-r--r-- 1 nines9 users 3.2K Nov 19 20:09 domain.key
drwxr-xr-x 8 nines9 users 4.0K Nov 19 19:57 .git
-rw-r--r-- 1 nines9 users  675 Nov 19 19:57 .gitignore
-rw-r--r-- 1 nines9 users  34K Nov 19 19:57 LICENSE
-rw-r--r-- 1 nines9 users  17K Nov 19 19:57 README.md
-rw-r--r-- 1 nines9 users  17K Nov 19 19:57 sign_csr.py
-rw-r--r-- 1 nines9 users    0 Nov 19 20:31 signed.crt
-rw-r--r-- 1 nines9 users 3.2K Nov 19 20:02 user.key
-rw-r--r-- 1 nines9 users  800 Nov 19 20:02 user.pub
```

I tryed this 2 times:
a) with www.9nines.net and 9nines.net (in the e-mail they confirmed both, but I tryed again)
b) with 9nines.net only. Same result.

**Comment by diafygi** [comment]
I feel like a bit of this output got cut off. Could please try pasting it again?

**Comment by huggi** [comment]
:+1:

**Comment by diafygi** [comment]
Did you paste the  openssl commands into another terminal window in the same directory? Was nines9.key also in the same directory? It looks you pasted them into the same terminal.

**Comment by huggi** [comment]
Yes to both. Everything is still there first thing I did was:
git clone <yourstuff> than I started with following the commands...

**Comment by diafygi** [comment]
Ok, can you please run `ls -lah` in the letsencrypt-nosudo directory to list the file contents. Also your original sign_csr.py command is cut off at the beginning of this bug report. Also, can you please paste from the start of the process, where you ran the git clone onward? Finally, Can you please try using markdown to style the pasted sections of output in monospace font so it's more clear what's going on?

**Comment by huggi** [comment]
Sure: $ ls -lah
total 112K
drwxr-xr-x  3 nines9 users 4.0K Nov 18 20:28 .
drwx---r-x 10 nines9 users 4.0K Nov 18 20:07 ..
-rw-r--r--  1 nines9 users 1.6K Nov 18 20:23 9nines.net.csr
-rw-r--r--  1 nines9 users 3.2K Nov 18 20:18 9nines.net.key
-rw-r--r--  1 nines9 users    0 Nov 18 20:22 domain.csr
drwxr-xr-x  8 nines9 users 4.0K Nov 18 19:50 .git
-rw-r--r--  1 nines9 users  675 Nov 18 19:50 .gitignore
-rw-r--r--  1 nines9 users  34K Nov 18 19:50 LICENSE
-rw-r--r--  1 nines9 users  800 Nov 18 19:57 nines9.pub
-rw-r--r--  1 nines9 users  17K Nov 18 19:50 README.md
-rw-r--r--  1 nines9 users    0 Nov 18 20:28 response_ATE3Yu.sig
-rw-r--r--  1 nines9 users  17K Nov 18 19:50 sign_csr.py
-rw-r--r--  1 nines9 users    0 Nov 18 20:23 signed.crt
-rw-r--r--  1 nines9 users 3.2K Nov 18 20:22 user.key
-rw-r--r--  1 nines9 users  800 Nov 18 20:18 user.pub

**Comment by diafygi** [comment]
I'm not seeing nines9.key in the directory. Where is it?

**Comment by huggi** [comment]
It's called: 9nines.net.key

**Comment by huggi** [comment]
But I will start from scratch again tomorrow morning.

**Comment by huggi** [comment]
Feedback from Support at my Hosting Provider, asking to run the command:

```
python sign_csr.py --public-key user.pub domain.csr
```

I'm afraid we can't do that for you.  The command is to run an HTTP
server independent of Apache.  First, this and Apache can't run at the
same time on port 80.  The only way to get this to work as written would
be to disable every website on the server.  Running a service on a
different port is also not permitted as a matter of security.

Sorry, but you're going to have to find a way for these "nosudo"
instructions to actually work without sudo.

My wishlist:
- Add "su" permissions in the requirements of your documentation, it does not work without them
- let's find a way to add a safe way to make letsencrypt happen with my provider, they provide a simple web interface to do the SSL zertification incl. self-signed certificates
- let's find a way to improve the script to work without "su"
- I'm keeping this ticket with my provider open until it works :)

**Comment by diafygi** [comment]
@huggi #20 should address your hosting provider limitation once it's merged in

**Comment by diafygi** [comment]
@huggi Did you run the python script on your server in "Seventh command: Terminal 1" above? If not, that's why the domain ownership verification failed.

**Comment by huggi** [comment]
@diafygi I will read them / and yes, but as I don't have su-permission I can't do that myself on my virtual host. And the provider is not willing to run it unless they know exactly what's going on.

Kind of a Chicken and Egg problem :) - will keep you posted.

**Comment by diafygi** [comment]
@huggi Can you please try https://gethttpsforfree.com? It's a browser-based client that has a file-based hosting option for verifying domain ownership. Hope that helps!

**Comment by huggi** [comment]
:+1:
