### ISSUE TITLE
Use “LE official client” “user registration” files?

### ISSUE THREAD

**Issue by ecc256** [diafygi/letsencrypt-nosudo#29]
Guys,
Anyway to use “user registration” files created by “LE official client”?
I’d do it myself, but my python knowledge is not good enough to dig through official client script...
I’ll appreciate, if you can show an easy way to do it :)

**Comment by diafygi** [comment]
The accounts for the official client are stored in `/etc/letsencrypt/accounts/...` so you should be able to change `accounts.key` in the copy/paste commands to the path to the LE key in that folder. Hope that helps!

**Comment by ecc256** [comment]
@diafygi,
I won’t ask if it was that simple.
There is private_key.json file there (on CentOS 7.0), my "private key" is a combination of fields probably, as any one of them is too short for 4096 bits key, IMO...
2 other files are meta.json regr.json

**Comment by diafygi** [comment]
@ecc256 Sorry, looks like the private key is stored in JWK format, so it needs to be converted to PEM. Node has a library that does this (https://www.npmjs.com/package/jwk-to-pem), and I'm sure there are others. Hope that helps!
