### ISSUE TITLE
Add a mode that will sign the keys.

### ISSUE THREAD

**Issue by skorokithakis** [diafygi/letsencrypt-nosudo#30]
Would it be possible to add a mode to LNS to run the commands to generate and sign the keys itself? It's not really that big a deal, but it would be faster if it I could just say "okay, you run and output a private key and a signed certificate at the end of the process". I would still need to run the web server, sure, but I usually just proxy the .well-known file to a specific port beforehand.

So, the process would be:

```
letsencrypt-nosudo --port=27318 <csr details>
```

Port 27318 would already be an HTTP proxy for the well-known file to the machine where this command would run, and the process would result to just two files, the private key and signed cert, which is much more plug-and-play.

**Comment by csware** [comment]
See https://github.com/corokada/letsencrypt-nosudo-auto

**Comment by skorokithakis** [comment]
Fantastic, thank you!

**Comment by diafygi** [comment]
Unfortunately, having access to private keys is out of scope for this project. Please use the official Let's Encrypt client or my acme-tiny client.

**Comment by skorokithakis** [comment]
Fair enough, thank you. Acme-tiny looks ideal.
