### ISSUE TITLE
Error when running sign_csr.py

### ISSUE THREAD

**Issue by jcatello** [diafygi/letsencrypt-nosudo#32]
I followed all the example steps to test and the outcome is:

$ python sign_csr.py --public-key user.pub domain.csr > domain.crt
Traceback (most recent call last):
  File "sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 26, in sign_csr
    nonce_req = urllib2.Request("{}/directory".format(CA))
ValueError: zero length field name in format

**Comment by diafygi** [comment]
I think this is because you are using python 2.6, and `.format()` is only available in python 2.7+
