### ISSUE TITLE
Use port >1024

### ISSUE THREAD

**Issue by pgl** [diafygi/letsencrypt-nosudo#34]
It would be really useful to be able to run the Python HTTP server on a port above 1024, so that non-root users could still verify their request.

**Comment by lfbayer** [comment]
Unfortunately it looks the ACME spec doesn't support requests to other ports, so the HTTP server has to listen on either 443 or 80. I don't think there is anything that this tool could do to get around that.

https://letsencrypt.github.io/acme-spec/#simple-http

**Comment by diafygi** [comment]
Yep, the `http-01` challenge that this script uses must be over port 80.
