### ISSUE TITLE
fails to generate csr

### ISSUE THREAD

**Issue by SvenRoederer** [diafygi/letsencrypt-nosudo#35]
just was able to do my 1st test after LE went public.

When teh script is generating the CSR it fails

> Requesting signature...
> Error: csr_data:
> POST https://acme-v01.api.letsencrypt.org/acme/new-cert
> {  
>     "header": {
>         "alg": "RS256",
>         "jwk": {
>             "e": "AQAB",
>             "kty": "RSA",

encoded data

> {"type":"urn:acme:error:malformed","detail":"Error unmarshaling certificate request","status":400}
> Traceback (most recent call last):
>   File "letsencrypt-nosudo-master/sign_csr.py", line 441, in <module>
>     signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
>   File "letsencrypt-nosudo-master/sign_csr.py", line 386, in sign_csr
>     resp = urllib2.urlopen(csr_url, csr_data)
>   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 445, in error
>     return self._call_chain(_args)
>   File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
>     result = func(_args)
>   File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by bavellone** [comment]
Also failing to generate CSR, but slightly different error:

```
Traceback (most recent call last):
  File "../letsencrypt-nosudo/sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "../letsencrypt-nosudo/sign_csr.py", line 242, in sign_csr
    test_nonce = urllib2.urlopen(nonce_req).headers['Replay-Nonce']
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by diafygi** [comment]
Howdy, can you please post the full encoded data? Thanks!

**Comment by diafygi** [comment]
You can also email it to me (my PGP key is on my website) if you don't want to publicly share it.

**Comment by toxinu** [comment]
Same error for me.
I'll send to you an email ([Keybase](https://keybase.io/socketubs)) with full POST Json data.

**Comment by diafygi** [comment]
@socketubs ok, it looks like the signature part of your request is blank. openssl is probably throwing an error. I've updated the script to print openssl errors. Can you please try it with the new script and let me know what the output is?

**Comment by diafygi** [comment]
@socketubs @SvenRoederer are you on Windows? Do you get any errors when you run the manual commands in your other terminal?

**Comment by toxinu** [comment]
@diafygi , I'm not on Windows (Ubuntu 15.10). But I think it's a mistake that it's due to an error during openssl commands while `sign_csr.py` asking for it.

It's working right now and I can't reproduce it.
I think you can simply ignore this issue.

**Comment by SvenRoederer** [comment]
sent a full log for a different servername I'd to get a cert for.

Running on a Debian Wheezy box with Python 2.7.3

**Comment by SvenRoederer** [comment]
Am Donnerstag, 3. Dezember 2015, 21:43:52 schrieb Daniel Roesler:

> Howdy, can you please post the full encoded data? Thanks!

Hi Daniel,

did the data I sent you helped to dig into the error I get?

Thanks Sven

**Comment by SvenRoederer** [comment]
problem is caused on the LetsEncrypt-side or my CSR generated by xca. 
https://github.com/letsencrypt/boulder/issues/1268

thanks for your work on this project

**Comment by quchao** [comment]
I got an error while requesting revocation,
maybe it caused by a same issue?
Thanks for your great work.

```
{"type":"urn:acme:error:malformed","detail":"Unable to read/verify body","status":400}
```
