### ISSUE TITLE
tempfolder instead of tempdirs

### ISSUE THREAD

**Issue by BenjaminHae** [diafygi/letsencrypt-nosudo#36]
How about using one tempfolder which contains all the temporary files?

This would have the advantage that the requests and the signatures would have nearly identical names(just different suffixes) so you could just go to that directory and
`for f in *.json; do
    openssl dgst -sha256 -sign user.key -out ${f%.json}.sig ${f}
done`
instead of calling openssl for every file on its own.

**Comment by diafygi** [comment]
eh, not wild about asking the user to copy/paste a bash for loop. There's not that many files to sign, and I like the idea of the user knowing how many things they are signing.

**Comment by BenjaminHae** [comment]
I would never ask the user to execute the bash loop, but users who understand what's going on _could_  do it.
This would make it much easier to use this script for automated renewal of the certificate as encouraged by let's encrypt in an article about ["Why ninety-day lifetimes for certificates?"](https://letsencrypt.org/2015/11/09/why-90-days.html)

> 1. [...]
> 2. They encourage automation, which is absolutely essential for ease-of-use. If we’re going to move the entire Web to HTTPS, we can’t continue to expect system administrators to manually handle renewals. Once issuance and renewal are automated, shorter lifetimes won’t be any less convenience than longer ones.

**Comment by diafygi** [comment]
This script is not intended to be automated, which would need access to private keys. If you need automation, please try another client like the official client or my acme-tiny client.

**Comment by BenjaminHae** [comment]
acme-tiny seems perfect. Thank you!
