### ISSUE TITLE
Error: Manual Commands

### ISSUE THREAD

**Issue by LekoArts** [diafygi/letsencrypt-nosudo#38]
Hello!

I stumbled across a problem occuring at Step 2. I successfully did:
python sign_csr.py --public-key user.pub domain.csr > signed.crt

After that I entered my email. But if I run the manual commands in a seperate command window this error occurs:

Error opening output file register_0h6rzr.sig
1384:error:02001020:system library:fopen:Broken pipe:.\crypto\bio\bss_file.c:168:fopen('register_0h6rzr.sig','wb')
1384:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:173:

I'm all new to this so if I forgot to mention some important sidenotes of my project, please tell me. And thanks in advance! :)

**Comment by diafygi** [comment]
Howdy, are you on Windows? If so, there's a python bug preventing from writing to the signature files (https://bugs.python.org/issue14243). If not, before you run the manual commands, can you check the directory you're in in that terminal to make sure all the files in the command are present?

**Comment by LekoArts** [comment]
Thanks for your fast reply! Yes, I'm using Windows 10 with Python 2.7.10. Should I instead try it on my Ubuntu (virtual machine) or do you have a solution/work-around for that bug?

**Comment by diafygi** [comment]
I do not have a solution for that bug, so please try this on your Ubuntu virtual machine.
