### ISSUE TITLE
Error creating new cert "Too many certificates already issued for: ddns.net"

### ISSUE THREAD

**Issue by katakombi** [diafygi/letsencrypt-nosudo#39]
I believe I did everything correctly, but I retrieve the following error when issuing the new cert:

Press Enter when you've got the python command running on your server...
Requesting verification for secret4u.ddns.net...
Waiting for secret4u.ddns.net challenge to pass...
Passed secret4u.ddns.net challenge!
Requesting signature...
Error: csr_data:
POST https://acme-v01.api.letsencrypt.org/acme/new-cert
{
    "header": {
        "alg": "RS256", 
        "jwk": {
            "e": "AQAB", 
            "kty": "RSA", 
            "n": "uihD9jAbqFuhRM2AcFfFpuMTouyTgC0bZw7HmA9d1_by_923QDYQvSb9z5t5u467bm4pLla5RxBg-xgPoKRZjhVD1AzfaXeQAMxREaO_BoxekWwLzt2AW8mu1cCX9a7UsvUCxt3NwCQ6PUkI2PuUpF0PSgKisUwWlMrf-qiOEdvyED85erSIvbN9uoZ2xQcAfbuShy_hvIQ4BUKfKw9UEWhxxn7t6t1t_A1Q_yWqND2uMtVpK9g3ujt5V-I9QIk_iLGrwlgPHuhp031j4JeeB9K-YE0PEjiAhzniz8GkMP2_-_yIsDZwkXlpb6g9aj5XesRrCUrLp8mx521V_7egLeFpv8hWyJe9Kx-5geIskIaD5ilfxsk_xbR8EGuvxommjR8AuvfaMUKac1MF3PUVgNiYSuSD1VSGd1lt3B3Rorv0BsdifyaUIaQpe0x_2XYNvZRMgnX889ZmCYpXE04BPUuyw2srGnVI8z0mOaGjKlVo47dkMH00NuYyu0VWUsV4PdURb8Oe7uuTKpcJEouzKUxjL2taXCHGDKemb9W7SYyFOZGnyajgg53uCT7pgamzBWcrsCWAPhl_1x8JmrJeJUP9HeudN19hEYutk9tshTZXdPQyeWckmenj6ZaUkS8QKCh3wUu2fzKFsc4FZbsvWW9bB1ebIKjW3J5pi9QHUYE"
        }
    }, 
    "payload": "ewogICAgImNzciI6ICJNSUlFWVRDQ0Fra0NBUUF3SERFYU1CZ0dBMVVFQXd3UmMyVmpjbVYwTkhVdVpHUnVjeTV1WlhRd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNzVU5LOFJDNXd4WlV5VHpFclRsV0lrS0hMejJUYmE1eW85SFBLMUNvUWo4THV4VnIxc0ZqaDFpX1cwazk0NmZGMEVkMXB0RVpDbmVfaEdxMnNYc1BNNU5sV3UwQ0VQRllqam9RZ0hWWGNOV09qa1pwMGl4Umk2Q0J6N1NyQm5EcnR4SDY2dTE3X3JMTFRTMnVTbldKVm1XMXk1VVpxQkc2bE90RmN6c1BSQXlZdEUwS25jS0s0cEJtMTVZVWRZRGFhTWFFYVEwVk1nNENsd1FpampFV25YUV85RnhVd0I2TExYd01NTTdGS0NXY2YtcWZqSEVxU0RDS3V3QWRPamZ0SEh4dXJ4ZGlOaEZheVZvZGQyOFpsNWdGZ2psMnM5aF9hQkU0Ny1xcGIya3IzN0hQSE4tZlhDSXhjMlp3eHBzV3V6OHl4N05CY21JSUdYUmZNR3pFQXhpd3JVTmdRenhGUGY5UlZaLS16b0NENTd4aXd1SzhzVTFDWUVtbUk4dlVia2VocXZyVElNcy1zOTZJeGotWDA3WmFYbFpYSk1wYmhobXlaeURaajhaQUdKYk14UWxTYkxUcUJ5cEd4dlhpa2Nza2VrVEZ4Ym5VcmRnVlNSekxrQmtjeXF1VXJRbmptWkxJQUs0MXVnWk5LZ2I4eUpXenZoTEtTQ2tnMkU3MXF6cEZFcEQ1QnFOTmx3eUMwbUwxYUNrMG1Na1lvaUN4NTNWNnVCSTV5clZxOWR6cTJNbFMyeUFlZ1pIaTMyQlZVQmtMTm1Bd2JhMW9TSXBhYW9OMWY2MS10MzVwV2xaNXdLVm1xbzJDVm8yOC1LQ0d3NjZDODdGZjJqVjB2NExBSkpfaDg2aWRuclhZRkY3QTNwdkR3ZnhlZkdGWmM1QTB5Zk9rMUpuQUtNd0lEQVFBQm9BQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBRzByV2hhUTBVZXZWYTBuV0JpNHZvMWNsamNMUmNrTFNUQmZlR2xValBjTmVYbkRnVE92bXRlc2t4eFdRNmt4Vlc2UmVfdHBTaEQ3cDNWcUZyNW9ZQlJCNmpna24zUXV5aGJkVk1PcGVZTmpLemxHRml1dDJSd29GREhWX3NkMmdqbDZjdlZGZHJRQUFGdVpYbWg5SU5DSUVEWWZ4SUFwZkxNZkFSQzB5V3hpazhjVjROREJxUTdCY292ckFOM19BTEpVYlRxVmhlYVVOZ2dzTF9IZzNrbjQ2cDJpRTJEdWUzZTJCcUk3eVItRzVLVkhFaFYzRUcyTWhBY0o1SWpfRE4wLTE2dnVleUNPTU1XMUhOQTRocG9Ocy1KV291UDUxMWxKamFWVnpOdW9sUmhpZ0VoVVpsQzh3LUVaa2xuVFd1SEhtcy1CVU53QW1uZHdBMG9ONG91dTZpaC1pY2p1amxFTU9Hdk9OZmhFbmx0aTJFTWp1R2gyNHN4Q0wzdDdhRlgtcE9OZFlVTFgxZTNOa0U5c0ppdXd0eUF1OXgyT293WjFldTRvQm91anFxdXRreWI1dFVDWmNlbmFGaVNkY1RobFVZTThJbGViWU5yOTU0T2hkVjhWQ1hKdzZtR3lVVm1zUzNVdmVoajl6X3pSVWVNMDR3bUUyR21QdzU4aXdpTmR4NFkwN3QtSE03aGJwWUQ3a0VaUi1weUJvRUFTamsycEQtT2EtMERLU3BCVURSVXhLU0U4eDNQSGtkaWRaNF92aEU3a1JoT0xwazF3SGNUdDFVQWYydUEySlpoUDhBeTNUbnR5TEt3UWhUS2JQdUlVX2xoUFBTd2dELXVkeHp2U2trR0NsNmtkbjNSaWZyWjF3Rkg2WVZ3R1pQUmtzYjhod0p6RWJidVUiLCAKICAgICJyZXNvdXJjZSI6ICJuZXctY2VydCIKfQ", 
    "protected": "ewogICAgImFsZyI6ICJSUzI1NiIsIAogICAgImp3ayI6IHsKICAgICAgICAiZSI6ICJBUUFCIiwgCiAgICAgICAgImt0eSI6ICJSU0EiLCAKICAgICAgICAibiI6ICJ1aWhEOWpBYnFGdWhSTTJBY0ZmRnB1TVRvdXlUZ0MwYlp3N0htQTlkMV9ieV85MjNRRFlRdlNiOXo1dDV1NDY3Ym00cExsYTVSeEJnLXhnUG9LUlpqaFZEMUF6ZmFYZVFBTXhSRWFPX0JveGVrV3dMenQyQVc4bXUxY0NYOWE3VXN2VUN4dDNOd0NRNlBVa0kyUHVVcEYwUFNnS2lzVXdXbE1yZi1xaU9FZHZ5RUQ4NWVyU0l2Yk45dW9aMnhRY0FmYnVTaHlfaHZJUTRCVUtmS3c5VUVXaHh4bjd0NnQxdF9BMVFfeVdxTkQydU10VnBLOWczdWp0NVYtSTlRSWtfaUxHcndsZ1BIdWhwMDMxajRKZWVCOUstWUUwUEVqaUFoem5pejhHa01QMl8tX3lJc0Rad2tYbHBiNmc5YWo1WGVzUnJDVXJMcDhteDUyMVZfN2VnTGVGcHY4aFd5SmU5S3gtNWdlSXNrSWFENWlsZnhza194YlI4RUd1dnhvbW1qUjhBdXZmYU1VS2FjMU1GM1BVVmdOaVlTdVNEMVZTR2QxbHQzQjNSb3J2MEJzZGlmeWFVSWFRcGUweF8yWFlOdlpSTWduWDg4OVptQ1lwWEUwNEJQVXV5dzJzckduVkk4ejBtT2FHaktsVm80N2RrTUgwME51WXl1MFZXVXNWNFBkVVJiOE9lN3V1VEtwY0pFb3V6S1V4akwydGFYQ0hHREtlbWI5VzdTWXlGT1pHbnlhamdnNTN1Q1Q3cGdhbXpCV2Nyc0NXQVBobF8xeDhKbXJKZUpVUDlIZXVkTjE5aEVZdXRrOXRzaFRaWGRQUXllV2NrbWVuajZaYVVrUzhRS0NoM3dVdTJmektGc2M0Rlpic3ZXVzliQjFlYklLalczSjVwaTlRSFVZRSIKICAgIH0sIAogICAgIm5vbmNlIjogInpldTc2Z2IxZkdDT3FRSFJUMzlwUzFTZ29WQzJKYjRRcXBON2Uzd0JiMVEiCn0", 
    "signature": "kh_MaUJUw8X-4p5B0RPgDpJPUkT9hKAA8aEb0DwUKQMufNs7ZNIFq5wliKSaI3HMfaxJeZC5WeKXneWlSTOhBvgv4LiYhGFyXsy8V591ydbe-UwGApUR8fpW9H2ZD9-o6aKTGNc4uy7pE6ghPcCao2ftFSyejfqhfeZC0iJsh-1I9yOGCT1mOhymGZ-bMBGwCc1Cz6ch7gmu4b9zwV-GiWgAbE5YGAkZeX9jgrpfGEjstI7FlpMglhScnSBHyYust87MocxOhJQnWl6wOOWpM51d1rgqVfTQYSx2rj8-6hhMuAh_peie2_TFxnNo-Fi8Vk3UmUAQqmf6ed4EwOKO5D9Gszgqd2d_yBZ2t41t4dfAue1C_u9AjNle7aR2QxWEg0wvAhbxCbZjHYMy15crbM2o3Fj7vLdYHdzCODlur1L9CDhs0b74BXT6Io8C5gC5OBv0NwQG8Qj9DThogfOkbllXWqgYielXWxyhU1jSdFs-OhxlUmBM-WdznbvmZvtFwLqQHmYJ03EjOXR-BdYlzMvGBTpaaAEKPpDzmLIgVWx8qfMFxzHZaVML16Go7OxkRhRlA1F9wk9eabEHfH3Uskym3QMdVymJl4Bi99-gV4uXDV1kCeFx-3-hUv0LgfBKnJNLFs96TN9mugx4zgppLnfddWr8uQib3xDKB8kPDrM"
}
{"type":"urn:acme:error:rateLimited","detail":"Error creating new cert :: Too many certificates already issued for: ddns.net","status":429}
Traceback (most recent call last):
  File "sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 386, in sign_csr
    resp = urllib2.urlopen(csr_url, csr_data)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 429: Unknown

Seems like there's a limit on domains at least those broad dyndns ones. Is it at all possible to issue certs for free domains? I'll switch to any dyndns provider as long as it is supported by letsencrypt.

Thanks for any hint

**Comment by diafygi** [comment]
See rate limiting information here: https://community.letsencrypt.org/t/beta-program-announcements/1631
