### ISSUE TITLE
python version >= 2.7 is required

### ISSUE THREAD

**Issue by pieska** [diafygi/letsencrypt-nosudo#40]
great client but It should be mentioned, that python 2.7 is required.

$ python --version
Python 2.6.6
$ python letsencrypt-nosudo-master/sign_csr.py -p user.pub -e user@domain.tld www.domain.tld.csr 
Traceback (most recent call last):
  File "letsencrypt-nosudo-master/sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "letsencrypt-nosudo-master/sign_csr.py", line 26, in sign_csr
    nonce_req = urllib2.Request("{}/directory".format(CA))
ValueError: zero length field name in format

**Comment by nabetse00** [comment]
Hello pieska, 

My server runs 2.6.6. The problem came from python changes from 2.6 to 2.7. 
in 2.6 "{}" isn't alowed so you have to put {0} {1} ... {n} matching the number of parameters.

I'll put a pull request if any one is interested !

Ciao ciao
