### ISSUE TITLE
python 2.6 compat

### ISSUE THREAD

**Issue by nabetse00** [diafygi/letsencrypt-nosudo#41]
Compatibility to python 2.6 changing {} to {0} .. {n} in .format lines

here is code since you do not accep branching or pull request

[sign_csr.txt](https://github.com/diafygi/letsencrypt-nosudo/files/52917/sign_csr.txt)

**Comment by diafygi** [comment]
Fixed in b08e3789c02ca3b4e50452df151f014241e815de

**Comment by nabetse00** [comment]
thank you !

2015-12-05 23:40 GMT+01:00 Daniel Roesler notifications@github.com:

> Fixed in b08e378
> https://github.com/diafygi/letsencrypt-nosudo/commit/b08e3789c02ca3b4e50452df151f014241e815de
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/diafygi/letsencrypt-nosudo/issues/41#issuecomment-162254356
> .

## 

Esteban Diez Laiz

_Antes de imprimir este e-mail piense bien si es necesario hacerlo, el
medioambiente es cosa de todos.Este mensaje de correo electrónico y sus
documentos adjuntos están dirigidos EXCLUSIVAMENTE a los destinatarios
especificados. La información contenida puede ser CONFIDENCIAL y/o estar
LEGALMENTE PROTEGIDA. Si usted recibe este mensaje por ERROR, por favor
comuníqueselo inmediatamente al remitente y ELIMÍNELO ya que usted NO ESTA
AUTORIZADO al uso, revelación, distribución, impresión o copia de toda o
alguna parte de la información contenida.This e-mail message and any
attached files are intended SOLELY for the addressee/s identified herein.
It may contain CONFIDENTIAL and/or LEGALLY PRIVILEGED. If you receive this
message in ERROR, please immediately notify the sender and DELETE it since
you ARE NOT AUTHORIZED to use, disclose, distribute, print or copy all or
part of the contained information._
