### ISSUE TITLE
Error running sign_csr.py

### ISSUE THREAD

**Issue by borisovg** [diafygi/letsencrypt-nosudo#49]
```
...
Requesting signature...
Error: csr_data:
POST https://acme-v01.api.letsencrypt.org/acme/new-cert
{
    "header": {
        "alg": "RS256", 
        "jwk": {
            "e": "AQAB", 
            "kty": "RSA", 
            "n": "SNIP"
        }
    }, 
    "payload": "SNIP", 
    "protected": "SNIP", 
    "signature": "SNIP"
}
{"type":"urn:acme:error:malformed","detail":"Error unmarshaling certificate request","status":400}
Traceback (most recent call last):
  File "./sign_csr.py", line 441, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "./sign_csr.py", line 386, in sign_csr
    resp = urllib2.urlopen(csr_url, csr_data)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by borisovg** [comment]
Possibly related: letsencrypt/letsencrypt#1726

**Comment by diafygi** [comment]
@borisovg This is usually related to the `payload` being incorrect. Can you please email me the full error message? You're welcome to use my public key on my personal website.

**Comment by diafygi** [comment]
@borisovg thanks for the email, it looks like your common name was not parsed correctly. It was formatted `Subject: CN=foo.com/emailAddress=user@foo.com`. Can you please remove the `/emailAddress=...` so the common name is just the domain name?

**Comment by borisovg** [comment]
This is entirely valid Subject field, see this for example:

https://en.wikipedia.org/wiki/X.509#Sample_X.509_certificates

**Comment by diafygi** [comment]
@borisovg Agreed, I see now that the regex should have parsed away the email section. Can you please email me the full output of the script? I suspect that something earlier is messing up.

**Comment by borisovg** [comment]
Sent - it's for a different domain, since I have already made a cert for the original domain using the official LE client, but error message is the same.

Is this an issue with upstream API - the bug I referenced above looks similar enough that it suggests it might be?

**Comment by diafygi** [comment]
Thanks, everything look ok on my end, so I think this might be an issue with the [boulder](https://github.com/letsencrypt/boudler) server. Probably failing at [`x509.ParseCertificateRequest(raw.CSR)`](https://github.com/letsencrypt/boulder/blob/d75c05141efc0a3b01fec8575d4374308c7d3cb3/core/objects.go#L127).

I'd like to file a bug with them. Can I use your CSR? If not, can you please generate a new log (like the one you just sent) with some throwaway keys?

**Comment by borisovg** [comment]
Feel free to use it - this one is only a test one.

**Comment by diafygi** [comment]
Thanks, filed https://github.com/letsencrypt/boulder/issues/1306

**Comment by diafygi** [comment]
@borisovg check out https://github.com/letsencrypt/boulder/issues/1306#issuecomment-167119318 Looks like you can't have `critical` as a flag.
