### ISSUE TITLE
noob-isms

### ISSUE THREAD

**Issue by JazzMaster** [diafygi/letsencrypt-nosudo#50]
I shall post rev #3 of the code in a minute...ok i lie...soon. SLEEEP!

Anyways, are you a complete noob here?Youre telling by the code that you know how to mangle up http(S) requests and process them (advanced python) but you cant even produce a simple syscall to the underlying os to exec() something? Its os.system() btw in python. exec, I believe is pascal. I forget what they call it in C, because i WRITE PASCAL. 

Take a line from Novell a few years back. Let the server maintain/watch the server. Linux is great at one thing very well, running. Running code, it doesnt matter. And by running, we AUTOMATE. Its like a McDonalds in here its so automated.

Seriously? The only part that cant be automated and requires user input is the random seed crap that needs to sit on the server. And I'll get to that part.
1) ssh user@servername.com (missing[new window])
2) this info is in ACME and the python spews out the file required location on error
3) seriously? RE-BIND (as root) an already RUNNING web service (apache/nginx)? Port 80 and 443 are ALREADY OPEN! Just put something THERE! And this kind of code prove that the script is not at all nosudo, but rather that it requires it. 

Yes, I can do better. AS I said, changes forthcoming. Revision #2 is already posted online.

It took me a minute after fighting with firefox and my DNS settings to make sure things were in order and what was working.I would up on the waitlist with one working cert.
Jokes on the script because thats all I need. DNS shortcut took care of the rest.

Dont get me started on firefox.
This is BASIC PYTHON. Any BOOK can teach you the basics.Im even going on a limb here and saying that some places online teach python(OH WAIT, they DO!) for FREE. I applaud the effort but LEARN to CODE.

**Comment by diafygi** [comment]
I honestly have no idea what you're saying. This project is not intended to be automated nor is it supposed to be run on your server. If you want those things, please use another client.

**Comment by JazzMaster** [comment]
I beg your pardon. Anything Linux is meant to be automated.I never said anything about running it on the server. I said you fuddled the code to REQUIRE ROOT access where its not needed at all, and I said your back-asswards attempt at modifying a ALREADY RUNNING process on a LIVE net-enabled machine was much more that a pointless waste. It was YOUR CODE that said run it on a server.

You called the other 'file mode'. Yes, LE did intend automation.Its thier system, they should make that determination. For the record GPL and Python is NOT the way to publish (mid you half assed) "personal secrets" to hack someone else's setup to do your bidding. Its your loss, not mine. If you wanted a "personal secret" method, go use something that compiles to bytecode and mark it non-free.Then you dont have to release the source. If you cant understand english, I cant help you.Basic language comprehension is a requirement is most countries I know of.

**Comment by 0rovan** [comment]
diafygi has created a tool by his liking. At least another 640+ people (at this point) including me like his tool and expressed this by staring the project. So it seems like he knows what he is doing. If you do not like that your recommendations for the project were not accepted do what I did and fork it. Or create your own script in whatever language with system calls of your liking. If you choose this path and choose pascal, let me know. I would be interested to see your code and maybe come back to pascal once again - it was the second language I have started learning when I was a kid.

But please stop being mean, get a hug, move on! And the why you write is way distant from proper understandable English.
