### ISSUE TITLE
Do not abort everything when a challenge verification failed

### ISSUE THREAD

**Issue by ThiefMaster** [diafygi/letsencrypt-nosudo#52]
This is **extremely** annoying. :angry:  I had a validation for 4 domains running and was running the wrong python server for one of them. Now I need to start everything from scratch, which includes temporarily taking down the proper webserver.

It would be _really_ great if your script offered to retry in case the validation failed.

**Comment by diafygi** [comment]
Retrying would require another signature and nonce, which I think complicates things too much in the code. Feel free to fork this project and modify as you need it.
