### ISSUE TITLE
Signed Cert Hang

### ISSUE THREAD

**Issue by cavkirov** [diafygi/letsencrypt-nosudo#54]
When I get to the point (Step 4 of: python sign_csr.py --public-key user.pub domain.csr > signed.crt) where I run on a separate terminal:
sudo python -c "import .....

It ends with:
socket.error: [Errno 98] Address already in use

**Comment by diafygi** [comment]
You already have a server running on port 80. Either you need to stop that server while running the command, or you need to use the `--file-based` option.
