### ISSUE TITLE
letsencrypt-nosudo added to Alpine Linux

### ISSUE THREAD

**Issue by itoffshore** [diafygi/letsencrypt-nosudo#59]
`letsencrypt-nosudo` was [added to Alpine Linux today](http://git.alpinelinux.org/cgit/aports/commit/?id=2aed621e02bb4948a7ff4f463f726941ceb40d4b).

If you can [create a `release`](https://help.github.com/articles/creating-releases/) in the future it will help me track updates with [Sibbel](https://sibbell.com/about/) so I can keep the `letsencrypt-nosudo` package updated in [Alpine](http://alpinelinux.org/).

To install `letsencrypt-nosudo` in an Alpine LXC container you just [enable the `testing` repo](http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Repository_pinning) & :

 `apk add letsencrypt-nosudo`.

**Comment by FlorianHeigl** [comment]
Awesome, really!

**Comment by itoffshore** [comment]
[yes](https://pkgs.alpinelinux.org/packages?name=letsencrypt-nosudo&repo=all&arch=x86_64&maintainer=all)

**Comment by diafygi** [comment]
I'll likely revist making releases setup configs when I upgrade this to ACME v2.
