### ISSUE TITLE
bunch of 502, gateway errors using sign_csr.py

### ISSUE THREAD

**Issue by tanimislam** [diafygi/letsencrypt-nosudo#6]
I get the following errors when using sign_csr.py, that I think I can isolate to bad gateways on servers that this tool uses:
- https://www.letsencrypt-demo.org/acme: 502 Bad Gateway
- https://www.letsencrypt-demo.org/terms: 502 Bad Gateway

**Comment by diafygi** [comment]
Yes, it appears that they are moving into the release domain.

**Comment by 0rovan** [comment]
This will not solve the whole issue, but the agreement URL required to be sent via JSON  works with:
https://letsencrypt.org/documents/LE-SA-v1.0-June-23-2015.pdf

The newer one would also probably work:
https://letsencrypt.org/documents/LE-SA-v1.0-July-27-2015.pdf
