### ISSUE TITLE
{"type":"urn:acme:error:malformed","detail":"JWS verification error","status":400}

### ISSUE THREAD

**Issue by Odel93** [diafygi/letsencrypt-nosudo#60]
Hi, when i try to execute :

python sign_csr.py --public-key user.pub domain.csr > signed.crt

it run, and ask me for email ( all seem okey ) .. but after that i got this :

 "signature": ""
}
{"type":"urn:acme:error:malformed","detail":"JWS verification error","status":400}
Traceback (most recent call last):
  File "sign_csr.py", line 446, in <module>
    signed_crt = sign_csr(args.public_key, args.csr_path, email=args.email, file_based=args.file_based)
  File "sign_csr.py", line 198, in sign_csr
    resp = urllib2.urlopen(reg_url, reg_data)
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
- i had the same problem with gethttpsforfree.com, but i solved it from an issue published here ( the thing of cachebuster .. ). But with the python app i cant solve it, and i think it's the same issue with what was happening with the web app ! THNK YOU ALL !!

**Comment by Odel93** [comment]
ps : i upgraded my python from 2.7.6 to 2.7.9 on ubuntu 14.04 LTS

**Comment by rkkoszewski** [comment]
Have you done the 
`.../www/.well-know/acme-challenge/(random-filename-generated-by-script)`
verification?

I had the same issue. Using `-f` in the command line may help you out if you're on a shared host.
Just read carefully what the script is telling you.

**Comment by thelapisfox** [comment]
I'm getting this error on step 3 as well. I have verified that I am following all the steps as listed but it does not work. I have attempted Step 3 6 times now.  

Edit: The error appears after I run the commands in second terminal.
