### ISSUE TITLE
Wildcard sub-domains not supported readme

### ISSUE THREAD

**Issue by tzeejay** [diafygi/letsencrypt-nosudo#61]
Hey,

I found #26 [Multiple Domains](#26) in which you explained that wildcards do not work with Let's Encrypt but I would like to see this stated in the readme. 

I have not looked at the Let's Encrypt specification but it makes sense. Would be nice if you could add it. I would do it myself and create a pull request but I thought it might be better if you do it in your writing style.

Thanks for the work on the script. Works incredibly well. I used it on 64-bit Ubuntu and OSX 10.10

**Comment by diafygi** [comment]
Correct, wildcards will not be supported by this script since Let's Encrypt does not support issuing wildcard domains using the `http-01` verification method.
