### ISSUE TITLE
Got 500 when email not set

### ISSUE THREAD

**Issue by fikr4n** [diafygi/letsencrypt-nosudo#69]
The protocol actually does not require `contact` field, so I remove (comment) it. However I got 500 server error without any further explanation. Could you help me?

**Comment by fikr4n** [comment]
I think this is the issue with letsencrypt server, because I can get my cert at [crt.sh](https://crt.sh). Let's close this issue :D. Thank you.

References:
https://github.com/letsencrypt/letsencrypt/issues/2597
https://community.letsencrypt.org/t/client-receives-error-creating-new-cert-message-from-server/3219

**Comment by diafygi** [comment]
I think this has been fixed on their side.
