### ISSUE TITLE
[request] renew script ?

### ISSUE THREAD

**Issue by ychaouche** [diafygi/letsencrypt-nosudo#73]
Thanks for the script. Should we renew our certificates by running the script again or ?

**Comment by jbwhaley** [comment]
Yes, please.

**Comment by anko** [comment]
Duplicate of https://github.com/diafygi/letsencrypt-nosudo/issues/55?

**Comment by diafygi** [comment]
Renewal can be done by just re-running `sign_csr.py` with the same CSR and public key files.
