### ISSUE TITLE
Syntax error or user error???

### ISSUE THREAD

**Issue by yurisa2** [diafygi/letsencrypt-nosudo#77]
tried to run as instructed on the readme..... got this...

```
python letsencrypt-nosudo/sign_csr.py --public-key user.pub domain.csr > signed.crt
  File "letsencrypt-nosudo/sign_csr.py", line 47
    pub_exp = "0{0}".format(pub_exp) if len(pub_exp) % 2 else pub_exp
                                      ^
SyntaxError: invalid syntax

```

Am I doing something wrong ?

**Comment by yurisa2** [comment]
Well, not exactly an error, but I had to run the "python" command using "python2.6" ... Thanks!

**Comment by cclambie** [comment]
I have a similar issue with Line 7.
I am using Python version 2.6.6 - maybe a newer version required.
Running on Crazy Domains shared hosting, any thoughts?
