### ISSUE TITLE
Python script does not work for IPv6

### ISSUE THREAD

**Issue by ckorn** [diafygi/letsencrypt-nosudo#78]
The python command to run the HTTP server only supports IPv4.

As Let's Encrypt can now also verify IPv6 only domains the client should also make it possible to do the certificate signing directly on the IPv6 host.

**Comment by diafygi** [comment]
When you copy and paste the `sudo python -c "import BaseHTTPServer;...` command to your server, all you should need to do is change `'0.0.0.0'` to `'::'`. Feel free to modify the code to do this yourself, but I will not likely change it in the master branch.
