### ISSUE TITLE
Add note about using cross-signed Intermediate Certificates to README

### ISSUE THREAD

**Issue by zachreizner** [diafygi/letsencrypt-nosudo#8]
What follows are the frustrations I had while setting up letsencrypt using your script, which I realize are my own fault. I suggest clarifying in your README the confusions I had in order to help the next poor soul with more ambition than brains in getting set up with letsencrypt :)

While using your tool I didn't realize I needed to append the cross-signed certificate to my certificate for the nginx config, and by the time I realized I needed that step, I had a hard time finding the cross-signed certificate. I wasn't even sure if the cross-signed certificate was something I needed to download or generate unique to my certificate (because I'm a TLS newbie).

I suggest a quick mention that the signed crt file will work in the future when all browsers trust the letsencrypt root, but currently one needs to grab the pem file labeled "Let’s Encrypt Authority X1 (IdenTrust cross-signed)" from https://letsencrypt.org/certificates/ and cat it to the back of the signed crt file. The reason I figured this out is because of the HN post from [lolware](https://lolware.net/2015/10/27/letsencrypt_go_live.html) has a link to the certificates page (sad aside: I had looked at that letsencrypt certificates page so many times and somehow missed that battery of useful pem files at the top).

Thanks for the useful tool. I think you did a great job and soem added notes  will hopefully make some people's use of it go more smoothly.

**Comment by diafygi** [comment]
Thanks! Done!
