### ISSUE TITLE
Stopped working in Windows

### ISSUE THREAD

**Issue by tab00** [diafygi/letsencrypt-nosudo#81]
I am on Windows 10 (and don't use Linux at all) and have used `sign_csr.py` with success a few times without problem. I have OpenSSL and Python for Windows already installed.

However yesterday when I needed to renew some certificates it no longer worked. I got errors like

> Error opening output file register_0h6rzr.sig
> 1384:error:02001020:system library:fopen:Broken pipe:.\crypto\bio\bss_file.c:168:fopen('register_0h6rzr.sig','wb')
> 1384:error:2006D002:BIO routines:BIO_new_file:system lib:.\crypto\bio\bss_file.c:173:

I made some changes so that the files are closed so that another process could write to them, and then have them reopened to resume processing. I could then renew my certificates, gladly, as they were going to expire within a day.

It would be good if you could officially support Windows by adjusting some of the simple file handling code, as everything else works fine for creating and renewing LetsEncrypt certificates.

Thank you.

**Comment by diafygi** [comment]
I don't support windows, but I'd guess you should use cygwin for python and openssl instead of the windows versions.
