### ISSUE TITLE
issue with  rsa -in user.key -pubout > user.pub

### ISSUE THREAD

**Issue by praxpk** [diafygi/letsencrypt-nosudo#82]
Hello,

I'm a complete newbie (you can call me a noob). I am not a programmer but trying to learn things. I have a website on a shared hosting platform (bluehost) and I'm trying this out as I have no access to root to get myself a letsencrypt ssl.

I tried running the second command on my server using putty and this is what I got

OpenSSL> rsa -in user.key -pubout > user.pub
unknown option >
rsa [options] <infile >outfile
where options are
 -inform arg     input format - one of DER NET PEM
 -outform arg    output format - one of DER NET PEM
 -in arg         input file
 -sgckey         Use IIS SGC key format
 -passin arg     input file pass phrase source
 -out arg        output file
 -passout arg    output file pass phrase source
 -des            encrypt PEM output with cbc des
 -des3           encrypt PEM output with ede cbc des using 168 bit key
 -aes128, -aes192, -aes256
                 encrypt PEM output with cbc aes
 -text           print the key in text
 -noout          don't print key out
 -modulus        print the RSA key modulus
 -check          verify key consistency
 -pubin          expect a public key in input file
 -pubout         output a public key
 -engine e       use engine e, possibly a hardware device.
error in rsa
OpenSSL>

Please help..

**Comment by diafygi** [comment]
It should be

`openssl rsa -in user.key -pubout > user.pub`

not

`OpenSSL> rsa -in user.key -pubout > user.pub`
