### ISSUE TITLE
Syntax error in:  pub_exp = "0{0}".format(pub_exp) if len(pub_exp) % 2 else pub_exp

### ISSUE THREAD

**Issue by TrueBoxGuy** [diafygi/letsencrypt-nosudo#86]
When I run "python sign_csr.py --public-key user.pub domain.csr > signed.crt" it says 
  File "sign_csr.py", line 44
    pub_exp = "0{0}".format(pub_exp) if len(pub_exp) % 2 else pub_exp

**Comment by ARogovsky** [comment]
+1
-sh-3.2$ python letsencrypt-nosudo/sign_csr.py --help
  File "letsencrypt-nosudo/sign_csr.py", line 47
    pub_exp = "0{0}".format(pub_exp) if len(pub_exp) % 2 else pub_exp
                                      ^
SyntaxError: invalid syntax
-sh-3.2$ python -V
Python 2.4.3
-sh-3.2$

**Comment by diafygi** [comment]
This script only works in python 2.7+
