### ISSUE TITLE
Action required: Let's Encrypt subscriber agreement URL Change

### ISSUE THREAD

**Issue by cpu** [diafygi/letsencrypt-nosudo#94]
Hi there,

I just opened https://github.com/diafygi/acme-tiny/issues/188 on the acme-tiny repository. That issue also affects this project:
https://github.com/diafygi/letsencrypt-nosudo/blob/8749f651907729d09cfbd1f0e54481a5b7b59036/sign_csr.py#L25

https://github.com/diafygi/letsencrypt-nosudo/blob/8749f651907729d09cfbd1f0e54481a5b7b59036/revoke_crt.py

Please refer to  https://github.com/diafygi/acme-tiny/issues/188 for details & suggested fixes.

**Comment by diafygi** [comment]
FYI, I'm going to review this stuff ASAP to make sure the TOS link change works.

**Comment by cpu** [comment]
Thanks @diafygi - I appreciate it!

**Comment by daniel-utilityapi** [comment]
Fixed in https://github.com/diafygi/letsencrypt-nosudo/commit/97fd44fe969bf8095595ded62c4f7e2844608f05

**Comment by diafygi** [comment]
Fixed in https://github.com/diafygi/letsencrypt-nosudo/commit/97fd44fe969bf8095595ded62c4f7e2844608f05
