### ISSUE TITLE
acme registration id?

### ISSUE THREAD

**Issue by aldocassola** [diafygi/letsencrypt-nosudo#95]
Hi,

Is there any way to retrieve the registration id the tool obtains from the CA when registering? It doesn't seem to be output anywhere. A post on letsencrypt website says you can retrieve it by sending a new reg request with the same key, but the exception raised in the script doesn't cointain this information. Thanks.

**Comment by diafygi** [comment]
You can inject a print statement in Step 7 to print out the registration response headers.

```python
        resp = urllib2.urlopen(reg_url, reg_data)
        print(resp.headers['Location']) # <-- insert this line
        result = json.loads(resp.read())
```

See https://tools.ietf.org/html/draft-ietf-acme-acme-10#section-7.3.1
