### ISSUE TITLE
Please rename project

### ISSUE THREAD

**Issue by bdaehlie** [diafygi/letsencrypt-nosudo#98]
For trademark reasons we cannot allow ACME clients to use our service's name (Let's Encrypt) in their name. Among other things, it can introduce confusion as to whether the client comes from us or someone else. We recommend you use the term "ACME" instead, in reference to the protocol implemented by your client. The term "ACME" is better because there are no trademark issues and the protocol is not specific to our CA so your client should work with other ACME-enabled CAs in the future.

I know this can be a pain but thanks for understanding.

**Comment by diafygi** [comment]
Renamed to acme-nosudo
